"""
Generate Omnia JET Sample Data - JET_Input.xlsx
Sheets: TB, Population (GL Detail), COA
All columns aligned with omnia_jet_pipeline.py expected column names.
"""

import os
import pandas as pd

base_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(base_dir, 'omnia_jet', 'JET_Input.xlsx')
os.makedirs(os.path.join(base_dir, 'omnia_jet'), exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# SHEET 1: Trial Balance (TB)
# Required: Account Number, Description, Opening Balance, Closing Balance, 
#           Currency, Closing Date  (+ optional FS categorization cols)
# ─────────────────────────────────────────────────────────────────────────────
tb_data = [
    # Assets
    {"Account Number": "10100000", "Description": "Cash and Bank - Current Account",  "Account Subtype": "Assets",      "FS Line Item": "Cash and cash equivalents",             "Opening Balance": 45200000.0,   "Closing Balance": 38750000.0,   "Debit": 12500000.0, "Credit": 18950000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "10200000", "Description": "Short-term Investments",            "Account Subtype": "Assets",      "FS Line Item": "Cash and cash equivalents",             "Opening Balance": 10000000.0,   "Closing Balance": 10000000.0,   "Debit": 0.0,        "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "11401000", "Description": "Trade Receivables - Domestic",      "Account Subtype": "Assets",      "FS Line Item": "Trade Receivables",                     "Opening Balance": 148500000.0,  "Closing Balance": 162000000.0,  "Debit": 42500000.0, "Credit": 29000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "11402000", "Description": "Trade Receivables - Export",        "Account Subtype": "Assets",      "FS Line Item": "Trade Receivables",                     "Opening Balance": 32000000.0,   "Closing Balance": 28500000.0,   "Debit": 8200000.0,  "Credit": 11700000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "11500000", "Description": "Prepaid Expenses",                  "Account Subtype": "Assets",      "FS Line Item": "Other current assets",                  "Opening Balance": 3800000.0,    "Closing Balance": 4200000.0,    "Debit": 2100000.0,  "Credit": 1700000.0,  "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "11600000", "Description": "Security Deposits",                 "Account Subtype": "Assets",      "FS Line Item": "Other non-current assets",              "Opening Balance": 5000000.0,    "Closing Balance": 5000000.0,    "Debit": 0.0,        "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "12100000", "Description": "Inventories - Raw Materials",       "Account Subtype": "Assets",      "FS Line Item": "Inventories",                           "Opening Balance": 62000000.0,   "Closing Balance": 58000000.0,   "Debit": 38000000.0, "Credit": 42000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "12200000", "Description": "Inventories - Finished Goods",      "Account Subtype": "Assets",      "FS Line Item": "Inventories",                           "Opening Balance": 28000000.0,   "Closing Balance": 31500000.0,   "Debit": 18500000.0, "Credit": 15000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "51001000", "Description": "Property, Plant & Machinery",       "Account Subtype": "Assets",      "FS Line Item": "Property, plant and equipment",         "Opening Balance": 540000000.0,  "Closing Balance": 558000000.0,  "Debit": 22000000.0, "Credit": 4000000.0,  "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "51002000", "Description": "Accumulated Depreciation",          "Account Subtype": "Assets",      "FS Line Item": "Property, plant and equipment",         "Opening Balance": -180000000.0, "Closing Balance": -201000000.0, "Debit": 0.0,        "Credit": 21000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    # Liabilities
    {"Account Number": "20100000", "Description": "Short-Term Borrowings",             "Account Subtype": "Liabilities", "FS Line Item": "Borrowings",                            "Opening Balance": -80000000.0,  "Closing Balance": -75000000.0,  "Debit": 25000000.0, "Credit": 20000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "20200000", "Description": "Long-Term Loans",                   "Account Subtype": "Liabilities", "FS Line Item": "Borrowings",                            "Opening Balance": -250000000.0, "Closing Balance": -230000000.0, "Debit": 20000000.0, "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "21100000", "Description": "Trade Payables - Domestic",         "Account Subtype": "Liabilities", "FS Line Item": "Trade Payables",                        "Opening Balance": -42000000.0,  "Closing Balance": -48000000.0,  "Debit": 35000000.0, "Credit": 41000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "21200000", "Description": "Accrued Liabilities",               "Account Subtype": "Liabilities", "FS Line Item": "Other current liabilities",             "Opening Balance": -18000000.0,  "Closing Balance": -21000000.0,  "Debit": 9000000.0,  "Credit": 12000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "21302630", "Description": "Output GST Clearing",               "Account Subtype": "Liabilities", "FS Line Item": "Other Payables",                        "Opening Balance": 0.0,          "Closing Balance": -2500000.0,   "Debit": 0.0,        "Credit": 2500000.0,  "Local Currency": "INR", "Closing Date": "03/31/2026"},
    # Equity
    {"Account Number": "1000001",  "Description": "Equity Share Capital - Rs.10",      "Account Subtype": "Liabilities", "FS Line Item": "Share Capital",                         "Opening Balance": -117200000.0, "Closing Balance": -117200000.0, "Debit": 0.0,        "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "1160001",  "Description": "Retained Earnings",                 "Account Subtype": "Liabilities", "FS Line Item": "Retained Earnings",                     "Opening Balance": -85000000.0,  "Closing Balance": -110000000.0, "Debit": 0.0,        "Credit": 25000000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    # Revenue
    {"Account Number": "41001400", "Description": "Sales Revenue - Domestic",          "Account Subtype": "Revenue",     "FS Line Item": "NET SALES REVENUE",                     "Opening Balance": -380000000.0, "Closing Balance": -445000000.0, "Debit": 500000.0,   "Credit": 65500000.0, "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "41001500", "Description": "Sales Revenue - Export",            "Account Subtype": "Revenue",     "FS Line Item": "NET SALES REVENUE",                     "Opening Balance": -42000000.0,  "Closing Balance": -50500000.0,  "Debit": 0.0,        "Credit": 8500000.0,  "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "41301200", "Description": "Interest Income",                   "Account Subtype": "Revenue",     "FS Line Item": "Finance income",                        "Opening Balance": -3800000.0,   "Closing Balance": -4600000.0,   "Debit": 0.0,        "Credit": 800000.0,   "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "41301600", "Description": "Miscellaneous Income",              "Account Subtype": "Revenue",     "FS Line Item": "Other operating income (expenses), net","Opening Balance": -1200000.0,   "Closing Balance": -1800000.0,   "Debit": 0.0,        "Credit": 600000.0,   "Local Currency": "INR", "Closing Date": "03/31/2026"},
    # Expenses
    {"Account Number": "50001000", "Description": "Cost of Goods Sold",               "Account Subtype": "Expenses",    "FS Line Item": "COST OF SALES AND SERVICES",            "Opening Balance": 215000000.0,  "Closing Balance": 248000000.0,  "Debit": 33000000.0, "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "52001000", "Description": "Employee Compensation",             "Account Subtype": "Expenses",    "FS Line Item": "General and administrative expenses",   "Opening Balance": 48000000.0,   "Closing Balance": 60000000.0,   "Debit": 12000000.0, "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "52002500", "Description": "Consultancy & Audit Fees",          "Account Subtype": "Expenses",    "FS Line Item": "General and administrative expenses",   "Opening Balance": 2500000.0,    "Closing Balance": 6000000.0,    "Debit": 3500000.0,  "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "52003000", "Description": "Depreciation Expense",              "Account Subtype": "Expenses",    "FS Line Item": "Depreciation and amortisation",         "Opening Balance": 16000000.0,   "Closing Balance": 21000000.0,   "Debit": 5000000.0,  "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
    {"Account Number": "52004000", "Description": "Finance Costs - Interest",          "Account Subtype": "Expenses",    "FS Line Item": "Finance costs",                         "Opening Balance": 8500000.0,    "Closing Balance": 11200000.0,   "Debit": 2700000.0,  "Credit": 0.0,        "Local Currency": "INR", "Closing Date": "03/31/2026"},
]
tb_df = pd.DataFrame(tb_data)

# ─────────────────────────────────────────────────────────────────────────────
# SHEET 2: Population / General Ledger Detail (JE)
# Required: Account Number, Document number, Document type, Accounting date,
#           Posting date, Amount in local currency, Currency code, User UD,
#           Text Header, Text Details
# ─────────────────────────────────────────────────────────────────────────────
je_data = [
    # Standard sales cycle
    {"GL Account": "11401000", "Accounting document": "RV2026000001", "Document type": "RV", "Accounting date": "04/05/2025", "Posting date": "04/05/2025", "Document date": "04/05/2025", "Fiscal Year": "2026", "Fiscal Period": "1", "Amount in local currency": "5250000.0", "Currency code": "INR", "Amount in group curr": "63126.0", "Group Currency": "USD", "Text Header": "Sales Invoice - Q1 FY26", "Text Details": "Domestic sales billing cycle",  "User UD": "JKUMAR", "Document type description": "Customer Invoice"},
    {"GL Account": "41001400", "Accounting document": "RV2026000001", "Document type": "RV", "Accounting date": "04/05/2025", "Posting date": "04/05/2025", "Document date": "04/05/2025", "Fiscal Year": "2026", "Fiscal Period": "1", "Amount in local currency": "-5250000.0","Currency code": "INR", "Amount in group curr": "-63126.0","Group Currency": "USD", "Text Header": "Sales Invoice - Q1 FY26", "Text Details": "Domestic sales billing cycle",  "User UD": "JKUMAR", "Document type description": "Customer Invoice"},

    {"GL Account": "11401000", "Accounting document": "RV2026000002", "Document type": "RV", "Accounting date": "05/12/2025", "Posting date": "05/12/2025", "Document date": "05/12/2025", "Fiscal Year": "2026", "Fiscal Period": "2", "Amount in local currency": "3800000.0", "Currency code": "INR", "Amount in group curr": "45734.0", "Group Currency": "USD", "Text Header": "Sales Invoice - Q1 FY26", "Text Details": "Standard billing run",          "User UD": "PSINGH", "Document type description": "Customer Invoice"},
    {"GL Account": "41001400", "Accounting document": "RV2026000002", "Document type": "RV", "Accounting date": "05/12/2025", "Posting date": "05/12/2025", "Document date": "05/12/2025", "Fiscal Year": "2026", "Fiscal Period": "2", "Amount in local currency": "-3800000.0","Currency code": "INR", "Amount in group curr": "-45734.0","Group Currency": "USD", "Text Header": "Sales Invoice - Q1 FY26", "Text Details": "Standard billing run",          "User UD": "PSINGH", "Document type description": "Customer Invoice"},

    # Export sales
    {"GL Account": "11402000", "Accounting document": "RV2026000010", "Document type": "RV", "Accounting date": "06/18/2025", "Posting date": "06/18/2025", "Document date": "06/18/2025", "Fiscal Year": "2026", "Fiscal Period": "3", "Amount in local currency": "8500000.0", "Currency code": "INR", "Amount in group curr": "102410.0","Group Currency": "USD", "Text Header": "Export Sales Invoice",     "Text Details": "Export batch to Middle East",    "User UD": "RVERMA", "Document type description": "Customer Invoice"},
    {"GL Account": "41001500", "Accounting document": "RV2026000010", "Document type": "RV", "Accounting date": "06/18/2025", "Posting date": "06/18/2025", "Document date": "06/18/2025", "Fiscal Year": "2026", "Fiscal Period": "3", "Amount in local currency": "-8500000.0","Currency code": "INR", "Amount in group curr": "-102410.0","Group Currency": "USD", "Text Header": "Export Sales Invoice",     "Text Details": "Export batch to Middle East",    "User UD": "RVERMA", "Document type description": "Customer Invoice"},

    # Purchase / COGS entries
    {"GL Account": "50001000", "Accounting document": "RE2026000020", "Document type": "RE", "Accounting date": "07/01/2025", "Posting date": "07/01/2025", "Document date": "06/28/2025", "Fiscal Year": "2026", "Fiscal Period": "4", "Amount in local currency": "12000000.0","Currency code": "INR", "Amount in group curr": "144480.0","Group Currency": "USD", "Text Header": "Purchase Invoice COGS",    "Text Details": "Raw material procurement",      "User UD": "ASHARMA","Document type description": "Vendor Invoice"},
    {"GL Account": "21100000", "Accounting document": "RE2026000020", "Document type": "RE", "Accounting date": "07/01/2025", "Posting date": "07/01/2025", "Document date": "06/28/2025", "Fiscal Year": "2026", "Fiscal Period": "4", "Amount in local currency": "-12000000.0","Currency code": "INR","Amount in group curr": "-144480.0","Group Currency": "USD","Text Header": "Purchase Invoice COGS",    "Text Details": "Payable to vendor - Hindustan Corp","User UD": "ASHARMA","Document type description": "Vendor Invoice"},

    # Employee payroll
    {"GL Account": "52001000", "Accounting document": "PC2026000030", "Document type": "PC", "Accounting date": "07/31/2025", "Posting date": "07/31/2025", "Document date": "07/31/2025", "Fiscal Year": "2026", "Fiscal Period": "4", "Amount in local currency": "4000000.0", "Currency code": "INR", "Amount in group curr": "48160.0", "Group Currency": "USD", "Text Header": "Payroll July 2025",        "Text Details": "Monthly salary disbursement",   "User UD": "SYSTEM", "Document type description": "Payroll Posting"},
    {"GL Account": "10100000", "Accounting document": "PC2026000030", "Document type": "PC", "Accounting date": "07/31/2025", "Posting date": "07/31/2025", "Document date": "07/31/2025", "Fiscal Year": "2026", "Fiscal Period": "4", "Amount in local currency": "-4000000.0","Currency code": "INR", "Amount in group curr": "-48160.0","Group Currency": "USD", "Text Header": "Payroll July 2025",        "Text Details": "Bank transfer - payroll",       "User UD": "SYSTEM", "Document type description": "Payroll Posting"},

    # Depreciation
    {"GL Account": "52003000", "Accounting document": "AF2026000040", "Document type": "AF", "Accounting date": "09/30/2025", "Posting date": "09/30/2025", "Document date": "09/30/2025", "Fiscal Year": "2026", "Fiscal Period": "6", "Amount in local currency": "5000000.0", "Currency code": "INR", "Amount in group curr": "60200.0", "Group Currency": "USD", "Text Header": "Depreciation Q2 FY26",     "Text Details": "Planned asset depreciation run","User UD": "BATCH",  "Document type description": "Depreciation Run"},
    {"GL Account": "51002000", "Accounting document": "AF2026000040", "Document type": "AF", "Accounting date": "09/30/2025", "Posting date": "09/30/2025", "Document date": "09/30/2025", "Fiscal Year": "2026", "Fiscal Period": "6", "Amount in local currency": "-5000000.0","Currency code": "INR", "Amount in group curr": "-60200.0","Group Currency": "USD", "Text Header": "Depreciation Q2 FY26",     "Text Details": "Accum. depreciation credit",   "User UD": "BATCH",  "Document type description": "Depreciation Run"},

    # Loan repayment
    {"GL Account": "20200000", "Accounting document": "ZP2026000050", "Document type": "ZP", "Accounting date": "10/15/2025", "Posting date": "10/15/2025", "Document date": "10/10/2025", "Fiscal Year": "2026", "Fiscal Period": "7", "Amount in local currency": "20000000.0","Currency code": "INR", "Amount in group curr": "240800.0","Group Currency": "USD", "Text Header": "Loan Repayment Q3",       "Text Details": "Principal repayment - HDFC Bank","User UD": "TRAO",   "Document type description": "Payment"},
    {"GL Account": "10100000", "Accounting document": "ZP2026000050", "Document type": "ZP", "Accounting date": "10/15/2025", "Posting date": "10/15/2025", "Document date": "10/10/2025", "Fiscal Year": "2026", "Fiscal Period": "7", "Amount in local currency": "-20000000.0","Currency code": "INR","Amount in group curr": "-240800.0","Group Currency": "USD","Text Header": "Loan Repayment Q3",       "Text Details": "Bank outflow - loan settlement","User UD": "TRAO",   "Document type description": "Payment"},

    # Interest income
    {"GL Account": "10200000", "Accounting document": "ZP2026000055", "Document type": "ZP", "Accounting date": "10/31/2025", "Posting date": "10/31/2025", "Document date": "10/31/2025", "Fiscal Year": "2026", "Fiscal Period": "7", "Amount in local currency": "800000.0",  "Currency code": "INR", "Amount in group curr": "9632.0",  "Group Currency": "USD", "Text Header": "Interest Income Oct",      "Text Details": "FD interest credited",          "User UD": "BATCH",  "Document type description": "Bank Receipt"},
    {"GL Account": "41301200", "Accounting document": "ZP2026000055", "Document type": "ZP", "Accounting date": "10/31/2025", "Posting date": "10/31/2025", "Document date": "10/31/2025", "Fiscal Year": "2026", "Fiscal Period": "7", "Amount in local currency": "-800000.0", "Currency code": "INR", "Amount in group curr": "-9632.0", "Group Currency": "USD", "Text Header": "Interest Income Oct",      "Text Details": "Interest income recognition",  "User UD": "BATCH",  "Document type description": "Bank Receipt"},

    # Audit/manual adjustment — non-standard (round amount, suspicious)
    {"GL Account": "41001400", "Accounting document": "AB2026000099", "Document type": "AB", "Accounting date": "03/31/2026", "Posting date": "03/31/2026", "Document date": "03/31/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "500000.0",  "Currency code": "INR", "Amount in group curr": "6020.0",  "Group Currency": "USD", "Text Header": "Auditor adjustment YE",   "Text Details": "Management override - revenue",  "User UD": "MGMT",   "Document type description": "Manual Journal"},
    {"GL Account": "21200000", "Accounting document": "AB2026000099", "Document type": "AB", "Accounting date": "03/31/2026", "Posting date": "03/31/2026", "Document date": "03/31/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "-500000.0", "Currency code": "INR", "Amount in group curr": "-6020.0", "Group Currency": "USD", "Text Header": "Auditor adjustment YE",   "Text Details": "Accrual reversal entry",        "User UD": "MGMT",   "Document type description": "Manual Journal"},

    # Post-closing entry (after 31 Mar)
    {"GL Account": "41001600", "Accounting document": "SA2026000101", "Document type": "SA", "Accounting date": "04/05/2026", "Posting date": "04/05/2026", "Document date": "04/05/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "600000.0",  "Currency code": "INR", "Amount in group curr": "7224.0",  "Group Currency": "USD", "Text Header": "Post-closing misc income", "Text Details": "Misc income recognised late",   "User UD": "RDESAI", "Document type description": "Manual Journal"},
    {"GL Account": "11500000", "Accounting document": "SA2026000101", "Document type": "SA", "Accounting date": "04/05/2026", "Posting date": "04/05/2026", "Document date": "04/05/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "-600000.0", "Currency code": "INR", "Amount in group curr": "-7224.0", "Group Currency": "USD", "Text Header": "Post-closing misc income", "Text Details": "Prepaid writedown",             "User UD": "RDESAI", "Document type description": "Manual Journal"},

    # Round-sum (suspicious) — 1,000,000 exactly
    {"GL Account": "52002500", "Accounting document": "SA2026000110", "Document type": "SA", "Accounting date": "01/15/2026", "Posting date": "01/15/2026", "Document date": "01/10/2026", "Fiscal Year": "2026", "Fiscal Period": "10","Amount in local currency": "1000000.0", "Currency code": "INR", "Amount in group curr": "12040.0", "Group Currency": "USD", "Text Header": "Consultancy Fees",         "Text Details": "External audit consultant",    "User UD": "SBPATIL","Document type description": "Manual Journal"},
    {"GL Account": "10100000", "Accounting document": "SA2026000110", "Document type": "SA", "Accounting date": "01/15/2026", "Posting date": "01/15/2026", "Document date": "01/10/2026", "Fiscal Year": "2026", "Fiscal Period": "10","Amount in local currency": "-1000000.0","Currency code": "INR", "Amount in group curr": "-12040.0","Group Currency": "USD", "Text Header": "Consultancy Fees",         "Text Details": "Bank payment to consultant",   "User UD": "SBPATIL","Document type description": "Manual Journal"},

    # GST clearing
    {"GL Account": "21302630", "Accounting document": "KR2026000120", "Document type": "KR", "Accounting date": "02/28/2026", "Posting date": "02/28/2026", "Document date": "02/28/2026", "Fiscal Year": "2026", "Fiscal Period": "11","Amount in local currency": "-2500000.0","Currency code": "INR", "Amount in group curr": "-30100.0","Group Currency": "USD", "Text Header": "GST Output Clearing",     "Text Details": "Quarterly GST settlement",      "User UD": "ASHARMA","Document type description": "Vendor Invoice"},
    {"GL Account": "10100000", "Accounting document": "KR2026000120", "Document type": "KR", "Accounting date": "02/28/2026", "Posting date": "02/28/2026", "Document date": "02/28/2026", "Fiscal Year": "2026", "Fiscal Period": "11","Amount in local currency": "2500000.0", "Currency code": "INR", "Amount in group curr": "30100.0", "Group Currency": "USD", "Text Header": "GST Output Clearing",     "Text Details": "Bank receipt GST refund",      "User UD": "ASHARMA","Document type description": "Vendor Invoice"},

    # Finance costs
    {"GL Account": "52004000", "Accounting document": "ZP2026000130", "Document type": "ZP", "Accounting date": "03/31/2026", "Posting date": "03/31/2026", "Document date": "03/31/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "2700000.0", "Currency code": "INR", "Amount in group curr": "32508.0", "Group Currency": "USD", "Text Header": "Interest Expense YE",     "Text Details": "Annual interest on term loan",  "User UD": "SYSTEM", "Document type description": "Payment"},
    {"GL Account": "20100000", "Accounting document": "ZP2026000130", "Document type": "ZP", "Accounting date": "03/31/2026", "Posting date": "03/31/2026", "Document date": "03/31/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "-2700000.0","Currency code": "INR", "Amount in group curr": "-32508.0","Group Currency": "USD", "Text Header": "Interest Expense YE",     "Text Details": "Short-term borrowing cost",     "User UD": "SYSTEM", "Document type description": "Payment"},

    # PPE addition
    {"GL Account": "51001000", "Accounting document": "AA2026000140", "Document type": "AA", "Accounting date": "08/20/2025", "Posting date": "08/20/2025", "Document date": "08/18/2025", "Fiscal Year": "2026", "Fiscal Period": "5", "Amount in local currency": "22000000.0","Currency code": "INR", "Amount in group curr": "264880.0","Group Currency": "USD", "Text Header": "Asset Addition - Machinery", "Text Details": "New CNC machine unit",         "User UD": "TRAO",   "Document type description": "Asset Posting"},
    {"GL Account": "21100000", "Accounting document": "AA2026000140", "Document type": "AA", "Accounting date": "08/20/2025", "Posting date": "08/20/2025", "Document date": "08/18/2025", "Fiscal Year": "2026", "Fiscal Period": "5", "Amount in local currency": "-22000000.0","Currency code": "INR","Amount in group curr": "-264880.0","Group Currency": "USD","Text Header": "Asset Addition - Machinery", "Text Details": "Vendor payable - Siemens India","User UD": "TRAO",   "Document type description": "Asset Posting"},

    # Inventory movement
    {"GL Account": "12100000", "Accounting document": "WA2026000150", "Document type": "WA", "Accounting date": "11/10/2025", "Posting date": "11/10/2025", "Document date": "11/10/2025", "Fiscal Year": "2026", "Fiscal Period": "8", "Amount in local currency": "-42000000.0","Currency code": "INR","Amount in group curr": "-505680.0","Group Currency": "USD","Text Header": "GI to Production",        "Text Details": "Raw material issued to shop floor","User UD": "BATCH", "Document type description": "Goods Issue"},
    {"GL Account": "50001000", "Accounting document": "WA2026000150", "Document type": "WA", "Accounting date": "11/10/2025", "Posting date": "11/10/2025", "Document date": "11/10/2025", "Fiscal Year": "2026", "Fiscal Period": "8", "Amount in local currency": "42000000.0", "Currency code": "INR", "Amount in group curr": "505680.0","Group Currency": "USD", "Text Header": "GI to Production",        "Text Details": "COGS - material consumed",      "User UD": "BATCH",  "Document type description": "Goods Issue"},

    # Weekend posting (suspicious)
    {"GL Account": "41301600", "Accounting document": "SA2026000200", "Document type": "SA", "Accounting date": "03/15/2026", "Posting date": "03/15/2026", "Document date": "03/15/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "600000.0",  "Currency code": "INR", "Amount in group curr": "7224.0",  "Group Currency": "USD", "Text Header": "Misc Income - Sunday",    "Text Details": "Unplanned misc income entry",   "User UD": "OCPL01", "Document type description": "Manual Journal"},
    {"GL Account": "11500000", "Accounting document": "SA2026000200", "Document type": "SA", "Accounting date": "03/15/2026", "Posting date": "03/15/2026", "Document date": "03/15/2026", "Fiscal Year": "2026", "Fiscal Period": "12","Amount in local currency": "-600000.0", "Currency code": "INR", "Amount in group curr": "-7224.0", "Group Currency": "USD", "Text Header": "Misc Income - Sunday",    "Text Details": "Offset to prepaid",             "User UD": "OCPL01", "Document type description": "Manual Journal"},
]
je_df = pd.DataFrame(je_data)

# ─────────────────────────────────────────────────────────────────────────────
# SHEET 3: Chart of Accounts (COA)
# Required: Account Number, Description, Financial Statement Category, FS Line Item
# ─────────────────────────────────────────────────────────────────────────────
coa_data = [
    {"Chart of Accounts": "JIOSAT", "Account Number": "10100000", "Description": "Cash and Bank - Current Account",  "Financial Statement Category": "Assets",      "FS Line Item": "Cash and cash equivalents",              "Account Grouping 1": "Cash & Bank",   "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "10200000", "Description": "Short-term Investments",           "Financial Statement Category": "Assets",      "FS Line Item": "Cash and cash equivalents",              "Account Grouping 1": "Investments",   "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "11401000", "Description": "Trade Receivables - Domestic",     "Financial Statement Category": "Assets",      "FS Line Item": "Trade Receivables",                      "Account Grouping 1": "Receivables",   "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "11402000", "Description": "Trade Receivables - Export",       "Financial Statement Category": "Assets",      "FS Line Item": "Trade Receivables",                      "Account Grouping 1": "Receivables",   "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "11500000", "Description": "Prepaid Expenses",                 "Financial Statement Category": "Assets",      "FS Line Item": "Other current assets",                   "Account Grouping 1": "Prepayments",   "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "11600000", "Description": "Security Deposits",                "Financial Statement Category": "Assets",      "FS Line Item": "Other non-current assets",               "Account Grouping 1": "Deposits",      "Account Grouping 2": "Non-Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "12100000", "Description": "Inventories - Raw Materials",      "Financial Statement Category": "Assets",      "FS Line Item": "Inventories",                            "Account Grouping 1": "Inventory",     "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "12200000", "Description": "Inventories - Finished Goods",     "Financial Statement Category": "Assets",      "FS Line Item": "Inventories",                            "Account Grouping 1": "Inventory",     "Account Grouping 2": "Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "51001000", "Description": "Property, Plant & Machinery",      "Financial Statement Category": "Assets",      "FS Line Item": "Property, plant and equipment",          "Account Grouping 1": "PPE - Gross",   "Account Grouping 2": "Non-Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "51002000", "Description": "Accumulated Depreciation",         "Financial Statement Category": "Assets",      "FS Line Item": "Property, plant and equipment",          "Account Grouping 1": "PPE - AccDep",  "Account Grouping 2": "Non-Current Assets"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "20100000", "Description": "Short-Term Borrowings",            "Financial Statement Category": "Liabilities", "FS Line Item": "Borrowings",                             "Account Grouping 1": "Borrowings",    "Account Grouping 2": "Current Liabilities"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "20200000", "Description": "Long-Term Loans",                  "Financial Statement Category": "Liabilities", "FS Line Item": "Borrowings",                             "Account Grouping 1": "Borrowings",    "Account Grouping 2": "Non-Current Liabilities"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "21100000", "Description": "Trade Payables - Domestic",        "Financial Statement Category": "Liabilities", "FS Line Item": "Trade Payables",                         "Account Grouping 1": "Payables",      "Account Grouping 2": "Current Liabilities"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "21200000", "Description": "Accrued Liabilities",              "Financial Statement Category": "Liabilities", "FS Line Item": "Other current liabilities",              "Account Grouping 1": "Accruals",      "Account Grouping 2": "Current Liabilities"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "21302630", "Description": "Output GST Clearing",              "Financial Statement Category": "Liabilities", "FS Line Item": "Other Payables",                         "Account Grouping 1": "Tax Payables",  "Account Grouping 2": "Current Liabilities"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "1000001",  "Description": "Equity Share Capital - Rs.10",     "Financial Statement Category": "Equity",      "FS Line Item": "Share Capital",                          "Account Grouping 1": "Share Capital", "Account Grouping 2": "Equity"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "1160001",  "Description": "Retained Earnings",                "Financial Statement Category": "Equity",      "FS Line Item": "Retained Earnings",                      "Account Grouping 1": "Reserves",      "Account Grouping 2": "Equity"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "41001400", "Description": "Sales Revenue - Domestic",         "Financial Statement Category": "Revenue",     "FS Line Item": "NET SALES REVENUE",                      "Account Grouping 1": "Revenue",       "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "41001500", "Description": "Sales Revenue - Export",           "Financial Statement Category": "Revenue",     "FS Line Item": "NET SALES REVENUE",                      "Account Grouping 1": "Revenue",       "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "41301200", "Description": "Interest Income",                  "Financial Statement Category": "Revenue",     "FS Line Item": "Finance income",                         "Account Grouping 1": "Other Income",  "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "41301600", "Description": "Miscellaneous Income",             "Financial Statement Category": "Revenue",     "FS Line Item": "Other operating income (expenses), net", "Account Grouping 1": "Other Income",  "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "50001000", "Description": "Cost of Goods Sold",              "Financial Statement Category": "Expenses",    "FS Line Item": "COST OF SALES AND SERVICES",             "Account Grouping 1": "COGS",          "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "52001000", "Description": "Employee Compensation",            "Financial Statement Category": "Expenses",    "FS Line Item": "General and administrative expenses",    "Account Grouping 1": "Staff Costs",   "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "52002500", "Description": "Consultancy & Audit Fees",         "Financial Statement Category": "Expenses",    "FS Line Item": "General and administrative expenses",    "Account Grouping 1": "Admin",         "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "52003000", "Description": "Depreciation Expense",             "Financial Statement Category": "Expenses",    "FS Line Item": "Depreciation and amortisation",          "Account Grouping 1": "Depreciation",  "Account Grouping 2": "Income Statement"},
    {"Chart of Accounts": "JIOSAT", "Account Number": "52004000", "Description": "Finance Costs - Interest",         "Financial Statement Category": "Expenses",    "FS Line Item": "Finance costs",                          "Account Grouping 1": "Finance Costs", "Account Grouping 2": "Income Statement"},
]
coa_df = pd.DataFrame(coa_data)

# Write all 3 sheets to Excel workbook
with pd.ExcelWriter(out_path, engine='openpyxl') as writer:
    tb_df.to_excel(writer, sheet_name='TB', index=False)
    je_df.to_excel(writer, sheet_name='Population', index=False)
    coa_df.to_excel(writer, sheet_name='COA', index=False)

print(f"Omnia JET sample data written to: {out_path}")
print(f"  TB   : {len(tb_df)} accounts")
print(f"  JE   : {len(je_df)} journal lines ({len(je_df)//2} balanced entries)")
print(f"  COA  : {len(coa_df)} chart of accounts records")
